server:
  port: 8080
  servlet:
    context-path: /
#reids配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 3000
    lettuce:
      pool :
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

#开发环境
breakpoint:
  upload:
    dir: F:/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880